// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloaking_detection.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cloaking_detection.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cloaking_detection {

namespace {

const ::google::protobuf::Descriptor* LearnedSites_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LearnedSites_reflection_ = NULL;
const ::google::protobuf::Descriptor* SitePatterns_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SitePatterns_reflection_ = NULL;
const ::google::protobuf::Descriptor* Pattern_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Pattern_reflection_ = NULL;
const ::google::protobuf::Descriptor* Item_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Item_reflection_ = NULL;
const ::google::protobuf::Descriptor* HtmlText_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HtmlText_reflection_ = NULL;
const ::google::protobuf::Descriptor* HtmlDom_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HtmlDom_reflection_ = NULL;
const ::google::protobuf::Descriptor* Feature_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Feature_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cloaking_5fdetection_2eproto() {
  protobuf_AddDesc_cloaking_5fdetection_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cloaking_detection.proto");
  GOOGLE_CHECK(file != NULL);
  LearnedSites_descriptor_ = file->message_type(0);
  static const int LearnedSites_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LearnedSites, site_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LearnedSites, timestamp_),
  };
  LearnedSites_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LearnedSites_descriptor_,
      LearnedSites::default_instance_,
      LearnedSites_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LearnedSites, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LearnedSites, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LearnedSites));
  SitePatterns_descriptor_ = file->message_type(1);
  static const int SitePatterns_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SitePatterns, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SitePatterns, pattern_),
  };
  SitePatterns_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SitePatterns_descriptor_,
      SitePatterns::default_instance_,
      SitePatterns_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SitePatterns, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SitePatterns, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SitePatterns));
  Pattern_descriptor_ = file->message_type(2);
  static const int Pattern_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pattern, mean_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pattern, std_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pattern, item_),
  };
  Pattern_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Pattern_descriptor_,
      Pattern::default_instance_,
      Pattern_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pattern, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pattern, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Pattern));
  Item_descriptor_ = file->message_type(3);
  static const int Item_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Item, simhash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Item, count_),
  };
  Item_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Item_descriptor_,
      Item::default_instance_,
      Item_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Item, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Item, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Item));
  HtmlText_descriptor_ = file->message_type(4);
  static const int HtmlText_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlText, word_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlText, bi_gram_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlText, tri_gram_),
  };
  HtmlText_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HtmlText_descriptor_,
      HtmlText::default_instance_,
      HtmlText_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlText, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlText, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HtmlText));
  HtmlDom_descriptor_ = file->message_type(5);
  static const int HtmlDom_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlDom, node_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlDom, bi_node_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlDom, tri_node_),
  };
  HtmlDom_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HtmlDom_descriptor_,
      HtmlDom::default_instance_,
      HtmlDom_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlDom, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HtmlDom, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HtmlDom));
  Feature_descriptor_ = file->message_type(6);
  static const int Feature_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, int_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, double_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, string_value_),
  };
  Feature_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Feature_descriptor_,
      Feature::default_instance_,
      Feature_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Feature, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Feature));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cloaking_5fdetection_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LearnedSites_descriptor_, &LearnedSites::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SitePatterns_descriptor_, &SitePatterns::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Pattern_descriptor_, &Pattern::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Item_descriptor_, &Item::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HtmlText_descriptor_, &HtmlText::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HtmlDom_descriptor_, &HtmlDom::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Feature_descriptor_, &Feature::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cloaking_5fdetection_2eproto() {
  delete LearnedSites::default_instance_;
  delete LearnedSites_reflection_;
  delete SitePatterns::default_instance_;
  delete SitePatterns_reflection_;
  delete Pattern::default_instance_;
  delete Pattern_reflection_;
  delete Item::default_instance_;
  delete Item_reflection_;
  delete HtmlText::default_instance_;
  delete HtmlText_reflection_;
  delete HtmlDom::default_instance_;
  delete HtmlDom_reflection_;
  delete Feature::default_instance_;
  delete Feature_reflection_;
}

void protobuf_AddDesc_cloaking_5fdetection_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030cloaking_detection.proto\022\022cloaking_det"
    "ection\"Q\n\014LearnedSites\022.\n\004site\030\001 \003(\0132 .c"
    "loaking_detection.SitePatterns\022\021\n\ttimest"
    "amp\030\002 \001(\t\"J\n\014SitePatterns\022\014\n\004name\030\001 \002(\t\022"
    ",\n\007pattern\030\002 \003(\0132\033.cloaking_detection.Pa"
    "ttern\"L\n\007Pattern\022\014\n\004mean\030\001 \002(\001\022\013\n\003std\030\002 "
    "\002(\001\022&\n\004item\030\003 \003(\0132\030.cloaking_detection.I"
    "tem\")\n\004Item\022\017\n\007simhash\030\001 \002(\004\022\020\n\005count\030\002 "
    "\001(\004:\0011\"\222\001\n\010HtmlText\022)\n\004word\030\001 \003(\0132\033.cloa"
    "king_detection.Feature\022,\n\007bi_gram\030\002 \003(\0132"
    "\033.cloaking_detection.Feature\022-\n\010tri_gram"
    "\030\003 \003(\0132\033.cloaking_detection.Feature\"\221\001\n\007"
    "HtmlDom\022)\n\004node\030\001 \003(\0132\033.cloaking_detecti"
    "on.Feature\022,\n\007bi_node\030\002 \003(\0132\033.cloaking_d"
    "etection.Feature\022-\n\010tri_node\030\003 \003(\0132\033.clo"
    "aking_detection.Feature\"V\n\007Feature\022\014\n\004na"
    "me\030\001 \002(\t\022\021\n\tint_value\030\002 \001(\005\022\024\n\014double_va"
    "lue\030\003 \001(\001\022\024\n\014string_value\030\004 \001(\t", 711);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cloaking_detection.proto", &protobuf_RegisterTypes);
  LearnedSites::default_instance_ = new LearnedSites();
  SitePatterns::default_instance_ = new SitePatterns();
  Pattern::default_instance_ = new Pattern();
  Item::default_instance_ = new Item();
  HtmlText::default_instance_ = new HtmlText();
  HtmlDom::default_instance_ = new HtmlDom();
  Feature::default_instance_ = new Feature();
  LearnedSites::default_instance_->InitAsDefaultInstance();
  SitePatterns::default_instance_->InitAsDefaultInstance();
  Pattern::default_instance_->InitAsDefaultInstance();
  Item::default_instance_->InitAsDefaultInstance();
  HtmlText::default_instance_->InitAsDefaultInstance();
  HtmlDom::default_instance_->InitAsDefaultInstance();
  Feature::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cloaking_5fdetection_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cloaking_5fdetection_2eproto {
  StaticDescriptorInitializer_cloaking_5fdetection_2eproto() {
    protobuf_AddDesc_cloaking_5fdetection_2eproto();
  }
} static_descriptor_initializer_cloaking_5fdetection_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int LearnedSites::kSiteFieldNumber;
const int LearnedSites::kTimestampFieldNumber;
#endif  // !_MSC_VER

LearnedSites::LearnedSites()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.LearnedSites)
}

void LearnedSites::InitAsDefaultInstance() {
}

LearnedSites::LearnedSites(const LearnedSites& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.LearnedSites)
}

void LearnedSites::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  timestamp_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LearnedSites::~LearnedSites() {
  // @@protoc_insertion_point(destructor:cloaking_detection.LearnedSites)
  SharedDtor();
}

void LearnedSites::SharedDtor() {
  if (timestamp_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete timestamp_;
  }
  if (this != default_instance_) {
  }
}

void LearnedSites::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LearnedSites::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LearnedSites_descriptor_;
}

const LearnedSites& LearnedSites::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

LearnedSites* LearnedSites::default_instance_ = NULL;

LearnedSites* LearnedSites::New() const {
  return new LearnedSites;
}

void LearnedSites::Clear() {
  if (has_timestamp()) {
    if (timestamp_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      timestamp_->clear();
    }
  }
  site_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LearnedSites::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.LearnedSites)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .cloaking_detection.SitePatterns site = 1;
      case 1: {
        if (tag == 10) {
         parse_site:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_site()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_site;
        if (input->ExpectTag(18)) goto parse_timestamp;
        break;
      }

      // optional string timestamp = 2;
      case 2: {
        if (tag == 18) {
         parse_timestamp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_timestamp()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->timestamp().data(), this->timestamp().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "timestamp");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.LearnedSites)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.LearnedSites)
  return false;
#undef DO_
}

void LearnedSites::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.LearnedSites)
  // repeated .cloaking_detection.SitePatterns site = 1;
  for (int i = 0; i < this->site_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->site(i), output);
  }

  // optional string timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->timestamp().data(), this->timestamp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "timestamp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->timestamp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.LearnedSites)
}

::google::protobuf::uint8* LearnedSites::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.LearnedSites)
  // repeated .cloaking_detection.SitePatterns site = 1;
  for (int i = 0; i < this->site_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->site(i), target);
  }

  // optional string timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->timestamp().data(), this->timestamp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "timestamp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->timestamp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.LearnedSites)
  return target;
}

int LearnedSites::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional string timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->timestamp());
    }

  }
  // repeated .cloaking_detection.SitePatterns site = 1;
  total_size += 1 * this->site_size();
  for (int i = 0; i < this->site_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->site(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LearnedSites::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LearnedSites* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LearnedSites*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LearnedSites::MergeFrom(const LearnedSites& from) {
  GOOGLE_CHECK_NE(&from, this);
  site_.MergeFrom(from.site_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LearnedSites::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LearnedSites::CopyFrom(const LearnedSites& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LearnedSites::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->site())) return false;
  return true;
}

void LearnedSites::Swap(LearnedSites* other) {
  if (other != this) {
    site_.Swap(&other->site_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LearnedSites::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LearnedSites_descriptor_;
  metadata.reflection = LearnedSites_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SitePatterns::kNameFieldNumber;
const int SitePatterns::kPatternFieldNumber;
#endif  // !_MSC_VER

SitePatterns::SitePatterns()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.SitePatterns)
}

void SitePatterns::InitAsDefaultInstance() {
}

SitePatterns::SitePatterns(const SitePatterns& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.SitePatterns)
}

void SitePatterns::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SitePatterns::~SitePatterns() {
  // @@protoc_insertion_point(destructor:cloaking_detection.SitePatterns)
  SharedDtor();
}

void SitePatterns::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void SitePatterns::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SitePatterns::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SitePatterns_descriptor_;
}

const SitePatterns& SitePatterns::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

SitePatterns* SitePatterns::default_instance_ = NULL;

SitePatterns* SitePatterns::New() const {
  return new SitePatterns;
}

void SitePatterns::Clear() {
  if (has_name()) {
    if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      name_->clear();
    }
  }
  pattern_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SitePatterns::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.SitePatterns)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pattern;
        break;
      }

      // repeated .cloaking_detection.Pattern pattern = 2;
      case 2: {
        if (tag == 18) {
         parse_pattern:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_pattern()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pattern;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.SitePatterns)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.SitePatterns)
  return false;
#undef DO_
}

void SitePatterns::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.SitePatterns)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .cloaking_detection.Pattern pattern = 2;
  for (int i = 0; i < this->pattern_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->pattern(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.SitePatterns)
}

::google::protobuf::uint8* SitePatterns::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.SitePatterns)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .cloaking_detection.Pattern pattern = 2;
  for (int i = 0; i < this->pattern_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->pattern(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.SitePatterns)
  return target;
}

int SitePatterns::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  // repeated .cloaking_detection.Pattern pattern = 2;
  total_size += 1 * this->pattern_size();
  for (int i = 0; i < this->pattern_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->pattern(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SitePatterns::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SitePatterns* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SitePatterns*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SitePatterns::MergeFrom(const SitePatterns& from) {
  GOOGLE_CHECK_NE(&from, this);
  pattern_.MergeFrom(from.pattern_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SitePatterns::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SitePatterns::CopyFrom(const SitePatterns& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SitePatterns::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->pattern())) return false;
  return true;
}

void SitePatterns::Swap(SitePatterns* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    pattern_.Swap(&other->pattern_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SitePatterns::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SitePatterns_descriptor_;
  metadata.reflection = SitePatterns_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Pattern::kMeanFieldNumber;
const int Pattern::kStdFieldNumber;
const int Pattern::kItemFieldNumber;
#endif  // !_MSC_VER

Pattern::Pattern()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.Pattern)
}

void Pattern::InitAsDefaultInstance() {
}

Pattern::Pattern(const Pattern& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.Pattern)
}

void Pattern::SharedCtor() {
  _cached_size_ = 0;
  mean_ = 0;
  std_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Pattern::~Pattern() {
  // @@protoc_insertion_point(destructor:cloaking_detection.Pattern)
  SharedDtor();
}

void Pattern::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Pattern::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pattern::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Pattern_descriptor_;
}

const Pattern& Pattern::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

Pattern* Pattern::default_instance_ = NULL;

Pattern* Pattern::New() const {
  return new Pattern;
}

void Pattern::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Pattern*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(mean_, std_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  item_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Pattern::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.Pattern)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double mean = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &mean_)));
          set_has_mean();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_std;
        break;
      }

      // required double std = 2;
      case 2: {
        if (tag == 17) {
         parse_std:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &std_)));
          set_has_std();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_item;
        break;
      }

      // repeated .cloaking_detection.Item item = 3;
      case 3: {
        if (tag == 26) {
         parse_item:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_item()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_item;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.Pattern)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.Pattern)
  return false;
#undef DO_
}

void Pattern::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.Pattern)
  // required double mean = 1;
  if (has_mean()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->mean(), output);
  }

  // required double std = 2;
  if (has_std()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->std(), output);
  }

  // repeated .cloaking_detection.Item item = 3;
  for (int i = 0; i < this->item_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->item(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.Pattern)
}

::google::protobuf::uint8* Pattern::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.Pattern)
  // required double mean = 1;
  if (has_mean()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->mean(), target);
  }

  // required double std = 2;
  if (has_std()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->std(), target);
  }

  // repeated .cloaking_detection.Item item = 3;
  for (int i = 0; i < this->item_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->item(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.Pattern)
  return target;
}

int Pattern::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double mean = 1;
    if (has_mean()) {
      total_size += 1 + 8;
    }

    // required double std = 2;
    if (has_std()) {
      total_size += 1 + 8;
    }

  }
  // repeated .cloaking_detection.Item item = 3;
  total_size += 1 * this->item_size();
  for (int i = 0; i < this->item_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->item(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pattern::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Pattern* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Pattern*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Pattern::MergeFrom(const Pattern& from) {
  GOOGLE_CHECK_NE(&from, this);
  item_.MergeFrom(from.item_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_mean()) {
      set_mean(from.mean());
    }
    if (from.has_std()) {
      set_std(from.std());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Pattern::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pattern::CopyFrom(const Pattern& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pattern::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->item())) return false;
  return true;
}

void Pattern::Swap(Pattern* other) {
  if (other != this) {
    std::swap(mean_, other->mean_);
    std::swap(std_, other->std_);
    item_.Swap(&other->item_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Pattern::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Pattern_descriptor_;
  metadata.reflection = Pattern_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Item::kSimhashFieldNumber;
const int Item::kCountFieldNumber;
#endif  // !_MSC_VER

Item::Item()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.Item)
}

void Item::InitAsDefaultInstance() {
}

Item::Item(const Item& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.Item)
}

void Item::SharedCtor() {
  _cached_size_ = 0;
  simhash_ = GOOGLE_ULONGLONG(0);
  count_ = GOOGLE_ULONGLONG(1);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Item::~Item() {
  // @@protoc_insertion_point(destructor:cloaking_detection.Item)
  SharedDtor();
}

void Item::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Item::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Item::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Item_descriptor_;
}

const Item& Item::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

Item* Item::default_instance_ = NULL;

Item* Item::New() const {
  return new Item;
}

void Item::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    simhash_ = GOOGLE_ULONGLONG(0);
    count_ = GOOGLE_ULONGLONG(1);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Item::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.Item)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 simhash = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &simhash_)));
          set_has_simhash();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_count;
        break;
      }

      // optional uint64 count = 2 [default = 1];
      case 2: {
        if (tag == 16) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.Item)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.Item)
  return false;
#undef DO_
}

void Item::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.Item)
  // required uint64 simhash = 1;
  if (has_simhash()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->simhash(), output);
  }

  // optional uint64 count = 2 [default = 1];
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.Item)
}

::google::protobuf::uint8* Item::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.Item)
  // required uint64 simhash = 1;
  if (has_simhash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->simhash(), target);
  }

  // optional uint64 count = 2 [default = 1];
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.Item)
  return target;
}

int Item::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 simhash = 1;
    if (has_simhash()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->simhash());
    }

    // optional uint64 count = 2 [default = 1];
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Item::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Item* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Item*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Item::MergeFrom(const Item& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_simhash()) {
      set_simhash(from.simhash());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Item::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Item::CopyFrom(const Item& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Item::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Item::Swap(Item* other) {
  if (other != this) {
    std::swap(simhash_, other->simhash_);
    std::swap(count_, other->count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Item::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Item_descriptor_;
  metadata.reflection = Item_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HtmlText::kWordFieldNumber;
const int HtmlText::kBiGramFieldNumber;
const int HtmlText::kTriGramFieldNumber;
#endif  // !_MSC_VER

HtmlText::HtmlText()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.HtmlText)
}

void HtmlText::InitAsDefaultInstance() {
}

HtmlText::HtmlText(const HtmlText& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.HtmlText)
}

void HtmlText::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HtmlText::~HtmlText() {
  // @@protoc_insertion_point(destructor:cloaking_detection.HtmlText)
  SharedDtor();
}

void HtmlText::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HtmlText::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HtmlText::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HtmlText_descriptor_;
}

const HtmlText& HtmlText::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

HtmlText* HtmlText::default_instance_ = NULL;

HtmlText* HtmlText::New() const {
  return new HtmlText;
}

void HtmlText::Clear() {
  word_.Clear();
  bi_gram_.Clear();
  tri_gram_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HtmlText::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.HtmlText)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .cloaking_detection.Feature word = 1;
      case 1: {
        if (tag == 10) {
         parse_word:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_word()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_word;
        if (input->ExpectTag(18)) goto parse_bi_gram;
        break;
      }

      // repeated .cloaking_detection.Feature bi_gram = 2;
      case 2: {
        if (tag == 18) {
         parse_bi_gram:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bi_gram()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_bi_gram;
        if (input->ExpectTag(26)) goto parse_tri_gram;
        break;
      }

      // repeated .cloaking_detection.Feature tri_gram = 3;
      case 3: {
        if (tag == 26) {
         parse_tri_gram:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_tri_gram()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_tri_gram;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.HtmlText)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.HtmlText)
  return false;
#undef DO_
}

void HtmlText::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.HtmlText)
  // repeated .cloaking_detection.Feature word = 1;
  for (int i = 0; i < this->word_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->word(i), output);
  }

  // repeated .cloaking_detection.Feature bi_gram = 2;
  for (int i = 0; i < this->bi_gram_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->bi_gram(i), output);
  }

  // repeated .cloaking_detection.Feature tri_gram = 3;
  for (int i = 0; i < this->tri_gram_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->tri_gram(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.HtmlText)
}

::google::protobuf::uint8* HtmlText::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.HtmlText)
  // repeated .cloaking_detection.Feature word = 1;
  for (int i = 0; i < this->word_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->word(i), target);
  }

  // repeated .cloaking_detection.Feature bi_gram = 2;
  for (int i = 0; i < this->bi_gram_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->bi_gram(i), target);
  }

  // repeated .cloaking_detection.Feature tri_gram = 3;
  for (int i = 0; i < this->tri_gram_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->tri_gram(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.HtmlText)
  return target;
}

int HtmlText::ByteSize() const {
  int total_size = 0;

  // repeated .cloaking_detection.Feature word = 1;
  total_size += 1 * this->word_size();
  for (int i = 0; i < this->word_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->word(i));
  }

  // repeated .cloaking_detection.Feature bi_gram = 2;
  total_size += 1 * this->bi_gram_size();
  for (int i = 0; i < this->bi_gram_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->bi_gram(i));
  }

  // repeated .cloaking_detection.Feature tri_gram = 3;
  total_size += 1 * this->tri_gram_size();
  for (int i = 0; i < this->tri_gram_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tri_gram(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HtmlText::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HtmlText* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HtmlText*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HtmlText::MergeFrom(const HtmlText& from) {
  GOOGLE_CHECK_NE(&from, this);
  word_.MergeFrom(from.word_);
  bi_gram_.MergeFrom(from.bi_gram_);
  tri_gram_.MergeFrom(from.tri_gram_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HtmlText::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HtmlText::CopyFrom(const HtmlText& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HtmlText::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->word())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->bi_gram())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->tri_gram())) return false;
  return true;
}

void HtmlText::Swap(HtmlText* other) {
  if (other != this) {
    word_.Swap(&other->word_);
    bi_gram_.Swap(&other->bi_gram_);
    tri_gram_.Swap(&other->tri_gram_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HtmlText::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HtmlText_descriptor_;
  metadata.reflection = HtmlText_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HtmlDom::kNodeFieldNumber;
const int HtmlDom::kBiNodeFieldNumber;
const int HtmlDom::kTriNodeFieldNumber;
#endif  // !_MSC_VER

HtmlDom::HtmlDom()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.HtmlDom)
}

void HtmlDom::InitAsDefaultInstance() {
}

HtmlDom::HtmlDom(const HtmlDom& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.HtmlDom)
}

void HtmlDom::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HtmlDom::~HtmlDom() {
  // @@protoc_insertion_point(destructor:cloaking_detection.HtmlDom)
  SharedDtor();
}

void HtmlDom::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HtmlDom::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HtmlDom::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HtmlDom_descriptor_;
}

const HtmlDom& HtmlDom::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

HtmlDom* HtmlDom::default_instance_ = NULL;

HtmlDom* HtmlDom::New() const {
  return new HtmlDom;
}

void HtmlDom::Clear() {
  node_.Clear();
  bi_node_.Clear();
  tri_node_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HtmlDom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.HtmlDom)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .cloaking_detection.Feature node = 1;
      case 1: {
        if (tag == 10) {
         parse_node:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_node()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_node;
        if (input->ExpectTag(18)) goto parse_bi_node;
        break;
      }

      // repeated .cloaking_detection.Feature bi_node = 2;
      case 2: {
        if (tag == 18) {
         parse_bi_node:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bi_node()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_bi_node;
        if (input->ExpectTag(26)) goto parse_tri_node;
        break;
      }

      // repeated .cloaking_detection.Feature tri_node = 3;
      case 3: {
        if (tag == 26) {
         parse_tri_node:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_tri_node()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_tri_node;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.HtmlDom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.HtmlDom)
  return false;
#undef DO_
}

void HtmlDom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.HtmlDom)
  // repeated .cloaking_detection.Feature node = 1;
  for (int i = 0; i < this->node_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->node(i), output);
  }

  // repeated .cloaking_detection.Feature bi_node = 2;
  for (int i = 0; i < this->bi_node_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->bi_node(i), output);
  }

  // repeated .cloaking_detection.Feature tri_node = 3;
  for (int i = 0; i < this->tri_node_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->tri_node(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.HtmlDom)
}

::google::protobuf::uint8* HtmlDom::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.HtmlDom)
  // repeated .cloaking_detection.Feature node = 1;
  for (int i = 0; i < this->node_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->node(i), target);
  }

  // repeated .cloaking_detection.Feature bi_node = 2;
  for (int i = 0; i < this->bi_node_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->bi_node(i), target);
  }

  // repeated .cloaking_detection.Feature tri_node = 3;
  for (int i = 0; i < this->tri_node_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->tri_node(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.HtmlDom)
  return target;
}

int HtmlDom::ByteSize() const {
  int total_size = 0;

  // repeated .cloaking_detection.Feature node = 1;
  total_size += 1 * this->node_size();
  for (int i = 0; i < this->node_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->node(i));
  }

  // repeated .cloaking_detection.Feature bi_node = 2;
  total_size += 1 * this->bi_node_size();
  for (int i = 0; i < this->bi_node_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->bi_node(i));
  }

  // repeated .cloaking_detection.Feature tri_node = 3;
  total_size += 1 * this->tri_node_size();
  for (int i = 0; i < this->tri_node_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tri_node(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HtmlDom::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HtmlDom* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HtmlDom*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HtmlDom::MergeFrom(const HtmlDom& from) {
  GOOGLE_CHECK_NE(&from, this);
  node_.MergeFrom(from.node_);
  bi_node_.MergeFrom(from.bi_node_);
  tri_node_.MergeFrom(from.tri_node_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HtmlDom::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HtmlDom::CopyFrom(const HtmlDom& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HtmlDom::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->node())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->bi_node())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->tri_node())) return false;
  return true;
}

void HtmlDom::Swap(HtmlDom* other) {
  if (other != this) {
    node_.Swap(&other->node_);
    bi_node_.Swap(&other->bi_node_);
    tri_node_.Swap(&other->tri_node_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HtmlDom::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HtmlDom_descriptor_;
  metadata.reflection = HtmlDom_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Feature::kNameFieldNumber;
const int Feature::kIntValueFieldNumber;
const int Feature::kDoubleValueFieldNumber;
const int Feature::kStringValueFieldNumber;
#endif  // !_MSC_VER

Feature::Feature()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cloaking_detection.Feature)
}

void Feature::InitAsDefaultInstance() {
}

Feature::Feature(const Feature& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:cloaking_detection.Feature)
}

void Feature::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int_value_ = 0;
  double_value_ = 0;
  string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Feature::~Feature() {
  // @@protoc_insertion_point(destructor:cloaking_detection.Feature)
  SharedDtor();
}

void Feature::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_value_;
  }
  if (this != default_instance_) {
  }
}

void Feature::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Feature::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Feature_descriptor_;
}

const Feature& Feature::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cloaking_5fdetection_2eproto();
  return *default_instance_;
}

Feature* Feature::default_instance_ = NULL;

Feature* Feature::New() const {
  return new Feature;
}

void Feature::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    int_value_ = 0;
    double_value_ = 0;
    if (has_string_value()) {
      if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        string_value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Feature::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cloaking_detection.Feature)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_int_value;
        break;
      }

      // optional int32 int_value = 2;
      case 2: {
        if (tag == 16) {
         parse_int_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int_value_)));
          set_has_int_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_double_value;
        break;
      }

      // optional double double_value = 3;
      case 3: {
        if (tag == 25) {
         parse_double_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &double_value_)));
          set_has_double_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_string_value;
        break;
      }

      // optional string string_value = 4;
      case 4: {
        if (tag == 34) {
         parse_string_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->string_value().data(), this->string_value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "string_value");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cloaking_detection.Feature)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cloaking_detection.Feature)
  return false;
#undef DO_
}

void Feature::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cloaking_detection.Feature)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 int_value = 2;
  if (has_int_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->int_value(), output);
  }

  // optional double double_value = 3;
  if (has_double_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->double_value(), output);
  }

  // optional string string_value = 4;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "string_value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->string_value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cloaking_detection.Feature)
}

::google::protobuf::uint8* Feature::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cloaking_detection.Feature)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 int_value = 2;
  if (has_int_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->int_value(), target);
  }

  // optional double double_value = 3;
  if (has_double_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->double_value(), target);
  }

  // optional string string_value = 4;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "string_value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->string_value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cloaking_detection.Feature)
  return target;
}

int Feature::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 int_value = 2;
    if (has_int_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->int_value());
    }

    // optional double double_value = 3;
    if (has_double_value()) {
      total_size += 1 + 8;
    }

    // optional string string_value = 4;
    if (has_string_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->string_value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Feature::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Feature* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Feature*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Feature::MergeFrom(const Feature& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_int_value()) {
      set_int_value(from.int_value());
    }
    if (from.has_double_value()) {
      set_double_value(from.double_value());
    }
    if (from.has_string_value()) {
      set_string_value(from.string_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Feature::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Feature::CopyFrom(const Feature& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Feature::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Feature::Swap(Feature* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(int_value_, other->int_value_);
    std::swap(double_value_, other->double_value_);
    std::swap(string_value_, other->string_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Feature::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Feature_descriptor_;
  metadata.reflection = Feature_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cloaking_detection

// @@protoc_insertion_point(global_scope)
